# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Emma J. Hudgins, PhD
email: emma.hudgins@carleton.ca

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

twitter_username: emmajhudgins
github_username:  emmajhudgins


# Build settings
markdown: kramdown
highlighter: rouge

collections:
        talks:
                output: true
        misc:
                output: true
plugins:
  - jekyll-assets
  - jekyll-remote-theme
remote_theme: daviddarnes/alembic@main